### ISSUE TITLE
Feature branches 

### ISSUE THREAD

**Issue by ericnguyen-adl** [ericnguyen-adl/Tafe20S102#1]
How to develop the feature branches (such as feat_PersonalInfo or feat_ContactDetails)?

**Comment by Jake7234** [comment]
Right click on your folder > TortiseGit > Create Branch... > type in feat_personalInfo into the Branch Name, based on HEAD (Master), add a description > click OK

**Comment by ericnguyen-adl** [comment]
Thanks Jake, I did that, I created my branch in local machine. What I actually ask is how should we develop that in the App. Will we need to create new interface, create new classes, where should we add codes, or will we need to connect to databases? I don't understand the requirement clearly.

**Comment by Jake7234** [comment]
My mistake. After a look at the program. We might need to add a new view for the interface, add the gets and sets in the accounts model. So maybe for you add: (in the Accounts Model)
[NotNull]
public string Email { get; set; }
Then put the code that actually adds, updates, deletes in a new ViewModel.
This is just a rough idea as the code is a lot more complected than I though it would be haha

**Comment by Jake7234** [comment]
After actually doing a large part of the code, I added a new model called PersonalInformation. A new view called PersonalInformationPage. The code to add/delete is in PersonalInformationPage.xaml.cs. I did not change the ViewModels. But I am lost on how to go about coding the update part.

**Comment by ericnguyen-adl** [comment]
I am thinking of adding few different pages (AddPage, UpdatePage, DeletePage) in views, a class called PersonalInfomation or ContactDetails and then AddViewModel, UpdateViewModel, DeleteViewModel. That looks to be time-consumed but can be done...
What I still don't know is how it actually connects to the other parts of the App? Thought?

**Comment by Jake7234** [comment]
In PersonalInformationPage.xaml.cs I added a SQLite connection. I stored the personal information in a table/list. How are you going to do it? When I wrote the code to create the table, that connects up to the PersonalInformation Model.

**Comment by ericnguyen-adl** [comment]
I think that is ok for me now. I add ContactDetails class, then ContactDetails View and then update the code similar with AccountsPage. The interface looks like this: 

![image](https://user-images.githubusercontent.com/61998845/77846041-c0e1af00-71fa-11ea-9fa8-58003db28f98.png)

**Comment by ericnguyen-adl** [comment]
Issue closed now. Both feature branches are working.
